DROP DATABASE `bj`;
CREATE DATABASE `bj` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `bj`;

DROP TABLE IF EXISTS tickets;
CREATE TABLE IF NOT EXISTS tickets (
  `id` INT UNSIGNED AUTO_INCREMENT,
  `user_id` int not null,
  `text` varchar (1024),
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `edited_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXIST users (
  `id` INT NOT NULL AUTO_INCREMENT,

  `name` varchar(100) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(100),

  `active` tinyint(1) DEFAULT 1,

  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `edited_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;